name: Build and Publish NPM Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: emscripten/emsdk:3.1.29
    steps:
      - uses: actions/checkout@v3
      - run: ./build_script.sh
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist

  publish:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/download-artifact@v3
        with:
          name: dist
      - run: npm install
      - run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
